kind: pipeline
name: images
type: kubernetes

steps:
- name: build
  image: plugins/docker
  environment:
  settings:
    purge: false
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: zillownyc/aws-s3-sync
    build_args:
    - AWS_CLI_VERSION=1.18.54
    tags:
    - latest
    - "1.0.0"
    - "1.0"

trigger:
  event:
  - push
  branch:
  - master
